# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProductTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProductTask
pod 'Alamofire'
pod 'Nuke', '9.2.0'
end
